services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    depends_on:
      - db
    networks:
      - dividis_network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file: ./frontend/.env
    networks:
      - dividis_network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: dividis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dividis_network


volumes:
  postgres_data:

networks:
  dividis_network:
    driver: bridge
